#
# $Id: GNUmakefile 22887 2012-09-21 01:30:42Z bylaska $
#

OBJ_OPTIMIZE =  string.o string_input.o

LIBRARY=liboptim.a

HEADERS=

USES_BLAS= string.F

include ../../config/makefile.h

include ../../config/makelib.h

showobj:
	echo "obj $(OBJ) "
	echo "obj_opt $(OBJ_OPTIMIZE)"
