#
#	$Id: MakeFile 19708 2010-10-29 18:04:21Z d3y133 $
#

# Note - collection of header files into this dir is currently being done
# by main makefile since this is "special"

# In this directory, clean does not do anything - we only want to get rid of
# the include files if there's a serious cleanup

clean:
	@echo clean does nothing in include dir

realclean:
	if exist "*.h" erase "*.h"
	if exist "*.fh" erase "*.fh"
