# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
#
	OBJ_OPTIMIZE = \
	deloc_driver.o \
	deloc.o \
	deloc_utils.o       

	LIBRARY = liboptim.a

	LIB_DEFINES =

	LIB_INCLUDES =

	USES_BLAS =

	HEADERS = 

include ../../config/makefile.h
include ../../config/makelib.h
