# $Id: GNUmakefile 21133 2011-09-30 23:37:07Z niri $

      OBJ = \
	dft_inpana.o \
	dft_rdinput.o \
        dft_input.o \
        tol_inp.o \
        grid_inp.o \
        xc_inp.o \
        conv_inp.o \
	cdft_inp.o \
	occup_input.o

     LIBRARY = libnwdft.a

 LIB_DEFINES =

LIB_INCLUDES = -I../include

#   USES_BLAS = xc_setquad.F

include ../../config/makefile.h
include ../../config/makelib.h
