# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $


LIBRARY =      libnwcutil.a

OBJ =		pstat_init.o	pstat_term.o	pstat_alloc.o \
		pstat_on.o	pstat_off.o		pstat_pr_all.o \
                pstat_free.o	pstat_pr_han.o	pstat_pr_det.o

HEADERS =	pstat.fh	pstat_consts.fh


include ../config/makefile.h
include ../config/makelib.h

