#
#        $Id: MakeFile 19708 2010-10-29 18:04:21Z d3y133 $
#


OBJ =          $(OBJDIR)\geom.obj \
               $(OBJDIR)\geom_input.obj \
               $(OBJDIR)\geom_input2.obj \
               $(OBJDIR)\geom_3d.obj \
               $(OBJDIR)\geom_2d.obj \
               $(OBJDIR)\geom_1d.obj \
               $(OBJDIR)\geom_hnd.obj \
               $(OBJDIR)\geom_numcore.obj \
               $(OBJDIR)\geom_checksum.obj \
               $(OBJDIR)\geom_freeze.obj \
               $(OBJDIR)\geom_symmol.obj \
               $(OBJDIR)\geom_print_ecce.obj

HEADERS =      geom.fh \
               geomP.fh

LIBRARY = nwcutil.lib

!INCLUDE ..\config\NTmakefile.h
!INCLUDE ..\config\NTmakelib.h
