#!/bin/bash

# Helper files
# (C) Jason Sewall : Intel
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software.  You can  use,
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".
# As a counterpart to the access to the source code and  rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty  and the software's author,  the holder of the
# economic rights,  and the successive licensors  have only  limited
# liability.
# In this respect, the user's attention is drawn to the risks associated
# with loading,  using,  modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean  that it is complicated to manipulate,  and  that  also
# therefore means  that it is reserved for developers  and  experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and,  more generally, to use and operate it in the
# same conditions as regards security.
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.


LF='
'

# First see if there is a version file (included in release tarballs),
# then try git-describe, then default.
if test x"$(git rev-parse --git-dir 2>/dev/null)" != x""
	then
	VN=$(git describe --abbrev=4 HEAD 2>/dev/null)
	if test x"$VN" == x"" -o x"$VN" == x"$LF"
	then
	VN=$(git log --pretty=format:"%h" -n 1)
	fi
	git update-index -q --refresh >/dev/null 2>/dev/null
	test -z "$(git diff-index --name-only HEAD --)" ||
	VN="$VN.dirty"
	echo "$VN">version.cand
	if test ! -f version -o -n "$(diff -q version.cand version 2>/dev/null)"
	then
	    echo "$VN">version
	fi
	rm -rf version.cand
else
    if test -f version
    then
	VN=$(cat version)
    else
	VN="unknown"
    fi
fi

echo $(expr "$VN" : v*'\(.*\)')
