OBJS:=\
/data/jwp/tmp/src/auto_decompo.o \
/data/jwp/tmp/src/cmod_mem.o \
/data/jwp/tmp/src/e_timer.o \
/data/jwp/tmp/src/constants.o \
/data/jwp/tmp/src/dmi_mpi_global.o \
/data/jwp/tmp/src/dmi_mpi.o \
/data/jwp/tmp/src/dmi_omp.o \
/data/jwp/tmp/src/exits_exit.o \
/data/jwp/tmp/src/exits.o \
/data/jwp/tmp/src/extreme.o \
/data/jwp/tmp/src/io_subs_flush.o \
/data/jwp/tmp/src/io_control.o \
/data/jwp/tmp/src/masscorr.o \
/data/jwp/tmp/src/main.o \
/data/jwp/tmp/src/tflow.o \
/data/jwp/tmp/src/io_miscsubs.o \
/data/jwp/tmp/src/io_subs.o \
/data/jwp/tmp/src/io_mpi.o \
