#
# $Id: GNUmakefile 19697 2010-10-29 16:57:34Z d3y133 $
#

 SUBDIRS = analytic

 OBJ = hess_blas.o hess_input.o
 
 OBJ_OPTIMIZE =  

   USES_BLAS = hess_blas.F 

   LIBRARY = libhessian.a

include ../config/makefile.h

include ../config/makelib.h

