#
#	$Id: MakeFile 19697 2010-10-29 16:57:34Z d3y133 $
#

SUBDIRS = .\ma .\tcgmsg-mpi \
          .\LinAlg\lapack+blas .\global .\pario

all: $(SUBDIRS)
	cd .\armci\src & nmake -nologo LIBDIR=..\..\lib\win32
	-!cd $** & nmake -nologo 

clean: $(SUBDIRS)
	-!cd $** & nmake -nologo clean
	cd .\armci\src & nmake -nologo LIBDIR=..\..\lib\win32 clean
	@erase /q .\include\*
	@erase /q *.stamp
